### ISSUE TITLE
Error (Xcode): 1 duplicate symbol for architecture arm64

### ISSUE THREAD

**Issue by wskkhn-hezhong** [shijia2118/speech_xf#1]
![image](https://github.com/shijia2118/speech_xf/assets/15773517/ddc79f32-ed63-4951-a476-1eb9561ce1b5)
请问这是什么原因

**Comment by wskkhn-hezhong** [comment]
![image](https://github.com/shijia2118/speech_xf/assets/15773517/a8c8c02b-6951-4ff7-94f8-2a276ece9b04)
这样替换一下,就可以与微信支付共存了

**Comment by wskkhn-hezhong** [comment]
还请作者能及时更改，万分感谢

**Comment by shijia2118** [comment]
好的，抱歉啊，最近太忙，没关注github。这周我会更新，请管足最新版本

**Comment by shijia2118** [comment]
好的，抱歉啊，最近太忙，没关注github。这周我会更新，请关注最新版本
